<?php
$helper = $this->helper('Logicrays\UpdateOrder\Helper\Data');
$optionLists = $helper->getOrderStatus($block->getOrder()->getId());
?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass) : ?>
        <?php $i++; ?>
        <td class="<?= /* @noEscape */ $columnClass ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>">
            <?= $block->getColumnHtml($_item, $columnName) ?>
            <?php
                if ($columnName == "lr-item-status") {
                    foreach ($optionLists as $key => $value) {
                        if($key == $_item->getLrItemStatus()){ ?>
                            <?= $block->escapeHtml(__($value)); ?>
                        <?php }
                    }
                }
            ?>
        </td>
    <?php endforeach; ?>
</tr>