<?php
/**
 * @category Mageants GiftCard
 * @package Mageants_GiftCard
 * @copyright Copyright (c) 2016 Mageants
 * @author Mageants Team <support@mageants.com>
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $block Mageants\GiftCard\Observer\GiftCategory
 */
?>
<?php
$viewModel = $block->getData("viewModel");

$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(\Magento\Catalog\Helper\Output::class); // @codingStandardsIgnoreLine
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div>
        <?= /* @noEscape */ __('We can\'t find products matching the selection.') ?>
        </div></div>
<?php else: ?>
    <?= /* @noEscape */  $block->getToolbarHtml() ?>
    <?= /* @noEscape */  $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */  $viewMode; ?> products-<?= /* @noEscape */  $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product):?>
                <?= /* @noEscape */ ($iterator++ == 1) ?
                    '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @noEscape */  $_product->getProductUrl() ?>"
                        class="product photo product-item-photo" tabindex="-1">
                        <?= /* @noEscape */  $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @noEscape */  $_product->getProductUrl() ?>">
                                <?= /* @noEscape */  $_helper->productAttribute(
                                    $_product,
                                    $_product->getName(),
                                    'name'
                                ); ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */  $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?= /* @noEscape */  $block->getProductPrice($_product) ?>
                        <?= /* @noEscape */  $block->getProductDetailsHtml($_product); ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"
                                <?= /* @noEscape */  strpos((string)$pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"
                                    <?= /* @noEscape */
                                    strpos((string)$pos, $viewMode . '-primary') ?
                                    $position : ''; ?>
                                    >
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <?php if ($_product->getTypeId() == "giftcertificate") { ?>
                                            <form  action="<?= /* @noEscape */  $_product->getProductUrl() ?>">
                                                
                                             </form>
                                            <button
                                                onclick="location.href = '<?= /* @noEscape */
                                                    $_product->getProductUrl() ?>';"
                                                title="<?= /* @noEscape */
                                                    $block->escapeHtml(__('View Gift Card')); ?>"
                                                class="action tocart primary">
                                                <span><?= /* @noEscape */  __('View Gift Card') ?></span>
                                            </button>
                                        <?php } else { ?>
                                            <form data-role="tocart-form"
                                                data-product-sku="<?= /* @noEscape */
                                                    $block->escapeHtml($_product->getSku()) ?>"
                                                action="<?= /* @noEscape */
                                                        $postParams['action'] ?>"
                                                method="post">
                                                <input type="hidden" name="product"
                                                        value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                <input type="hidden"
                                                    name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                    value="<?= /* @noEscape */
                                                    $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                
                                            </form>
                                            <button 
                                                onclick="location.href = '<?= /* @noEscape */
                                                $_product->getProductUrl() ?>';"
                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                class="action tocart primary">
                                                    <span><?= /* @noEscape */ __('Add to Cart') ?></span>
                                                </button>
                                        <?php } ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span>
                                                <?= /* @noEscape */  __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span>
                                                <?= /* @noEscape */  __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                
                            </div>
                            
                        </div>
                    </div>
                </div>
                <?= /* @noEscape */ ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= /* @noEscape */  $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
