<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Items\Column\Name
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('catalogHelper');
?>
<?php if ($_item = $block->getItem()): ?>
    <div id="order_item_<?= (int) $_item->getId() ?>_title"
         class="product-title">
        <?= $block->escapeHtml($_item->getName()) ?>
    </div>
    <div class="product-sku-block">
        <span><?= $block->escapeHtml(__('SKU'))?>:</span>
        <?= /* @noEscape */ implode('<br />', $catalogHelper->splitSku($block->escapeHtml($block->getSku()))) ?>
    </div>

    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php $count = 0; ?>
            <?php foreach ($block->getOrderOptions() as $_option): ?>
                <?php $count++;
                if($count <= 2){
                ?>
                <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?= /* @noEscape */ $block->getCustomizedOptionValue($_option) ?>
                    <?php else: ?>
                        <?php $_option = $block->getFormattedOption($_option['value']); ?>
                        <?php $dots = 'dots' . uniqid(); ?>
                        <?php $id = 'id' . uniqid(); ?>
                        <?= $block->escapeHtml($_option['value'], ['a', 'br']) ?>
                        <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                            <span id="<?= /* @noEscape */ $dots; ?>"> ...</span>
                            <span id="<?= /* @noEscape */ $id; ?>">
                                <?= $block->escapeHtml($_option['remainder'], ['a']) ?>
                            </span>
                            <?php $scriptString = <<<script
                                require(['prototype'], function() {

script;
                            $scriptString .= "$('" . /* @noEscape */ $id . "').hide();" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                             "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $id . "').show();});" .
                              PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $dots .
                                 "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $id .
                                 "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $dots .
                                 "').show();});" . PHP_EOL . "});" . PHP_EOL;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
                <?php }
                    else{ ?>
                        <span style="display:none" class="full-content_<?= (int) $_item->getId() ?>">
                        <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
                        <dd>
                            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                                <?= /* @noEscape */ $block->getCustomizedOptionValue($_option) ?>
                            <?php else: ?>
                                <?php $_option = $block->getFormattedOption($_option['value']); ?>
                                <?php $dots = 'dots' . uniqid(); ?>
                                <?php $id = 'id' . uniqid(); ?>
                                <?= $block->escapeHtml($_option['value'], ['a', 'br']) ?>
                                <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                                    <span id="<?= /* @noEscape */ $dots; ?>"> ...</span>
                                    <span id="<?= /* @noEscape */ $id; ?>">
                                        <?= $block->escapeHtml($_option['remainder'], ['a']) ?>
                                    </span>
                                    <?php $scriptString = <<<script
                                        require(['prototype'], function() {

        script;
                                    $scriptString .= "$('" . /* @noEscape */ $id . "').hide();" . PHP_EOL;
                                    $scriptString .= "$('" . /* @noEscape */ $id .
                                    "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $id . "').show();});" .
                                    PHP_EOL;
                                    $scriptString .= "$('" . /* @noEscape */ $id .
                                        "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $dots .
                                        "').hide();});" . PHP_EOL;
                                    $scriptString .= "$('" . /* @noEscape */ $id .
                                        "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $id .
                                        "').hide();});" . PHP_EOL;
                                    $scriptString .= "$('" . /* @noEscape */ $id .
                                        "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $dots .
                                        "').show();});" . PHP_EOL . "});" . PHP_EOL;
                                    ?>
                                    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </dd>
                        </span>

                    <?php } ?>
            <?php endforeach; ?>
                        
        </dl>
        <?php if($count >= 3){ ?>
                            <dt><dd><b><span class="read_more" style="cursor: pointer;" onclick="AddReadMore(<?= (int) $_item->getId() ?>)" id="<?= (int) $_item->getId() ?>">Read more</span></b></dd></dt>
                            <?php }
                        ?>
    <?php endif; ?>
    <?= $block->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>
<script type="text/javascript">
    function AddReadMore(itemId) {
        jQuery(".full-content_"+itemId).slideToggle();
        var readMore = jQuery("#"+itemId).text();
        if(readMore == "Read more"){
            jQuery("#"+itemId).text("Read less");
        }
        else{
            jQuery("#"+itemId).text("Read more");
        }
    }
</script>