
<?php $gridrecords = $block->getCustomerWalletCollection();?>

<div class="page-main-actions">
    <div class="page-actions">
        <div class="page-actions-inner">
            <strong class="title">Wallet Balance: <?= $block->escapeHtml(__($block->getCurrencySymbol()." ".$block->getRemainWalletAmount())) ?></strong>
        </div>
    </div>
</div>
<?php if ($gridrecords && sizeof($gridrecords)): ?>
    <table class="admin__table-secondary">
        <thead>
            <tr>
                <th scope="col" class="col id"> <?= /** noEscap */ __('ID') ?></th>
                <th scope="col" class="col amount"> <?= /** noEscap */ __('Amount') ?></th>
                <th scope="col" class="col note"> <?= /** noEscap */ __('Note') ?></th>
                <th scope="col" class="col status"> <?= /** noEscap */ __('Status') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach ($gridrecords as $gridrecord): ?>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                    <?= /** noEscap */ $gridrecord->getId() ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Amount')) ?>" class="col amount">
                    <?= /** noEscap */ $block->getCurrencySymbol(); ?>
                    <?= /** noEscap */ $gridrecord->getAmount(); ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Note')) ?>" class="col note">
                    <?php if ($gridrecord->getOrderid()):?>
                        <?= /** noEscap */ $gridrecord->getNote();?>
                        <a href="<?= /** noEscap */ $block->getViewOrderLink($gridrecord->getOrderid());?>">
                            #<?= /** noEscap */ $gridrecord->getOrderid(); ?>
                        </a>
                    <?php else: ?>
                        <?= /** noEscap */ $gridrecord->getNote();?>
                    <?php endif; ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Status')) ?>"
                    class="col status" id="status_<?= /** noEscap */ $gridrecord->getStatus(); ?>">
                    <?php if ($gridrecord->getStatus() == 0): ?>
                        <span id="wallet-pending"><?= $block->escapeHtml(__('Pending')) ?></span>
                    <?php elseif ($gridrecord->getStatus() == 1): ?>
                        <span class="wallet-credited" id="wallet-credited">
                            <?= $block->escapeHtml(__('Credited')) ?>
                        </span>
                    <?php elseif ($gridrecord->getStatus() == 2): ?>
                        <span id="wallet-canceled"><?= $block->escapeHtml(__('Canceled')) ?></span>
                    <?php elseif ($gridrecord->getStatus() == 4): ?>
                        <span id="wallet-debited"><?= $block->escapeHtml(__('Debited')) ?></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom">
            <?= /** noEscap */ $block->getPagerHtml(); ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <span>
            <?= /** noEscap */ __('No any Wallet transaction found.'); ?>
        </span>
    </div>
<?php endif; ?>
