<div id="myModal" class="modal ajax-forgot-form">
  <!-- Modal content -->
  <div class="mobile-modal-content">
    <div class="closediv"><span class="close">&times;</span></div>
    <div class="ajax-forgot-content">
    	<div id="ajaxlogin-forgot-window" class="login-window account-login">
            <div class="forgotmobileget">
            		 <div class="blankerror error" style="display:none">
                     	<span><?php echo __("Required fields cannot be empty");?></span>
                     </div>
            		 <div class="forgotmobileerror error" style="display:none">
                     	<span><?php echo __("Mobile Number Doesn't Exist");?></span>
                     </div>
                     <div class="page-title">
                        <span><?php
                        
                         echo __('Forgot Password') ?></span>
                    </div>
                     
                    <div class="otp-content input-box">
                     <label for="forgotmob" class="required"><em>*</em><?php echo __('Mobile Number') ?></label>
                     <div class="form-gorup">
                     <select name="countryCodeForgot" id="country-code-forgot">
                        <option value="+61"><?php echo __('+61') ?></option>
                        <option value="+43"><?php echo __('+43') ?></option>
                        <option value="+973"><?php echo __('+973') ?></option>
                        <option value="+880"><?php echo __('+880') ?></option>
                        <option value="+32"><?php echo __('+32') ?></option>
                        <option value="+1"><?php echo __('+1') ?></option>
                        <option value="+357"><?php echo __('+357') ?></option>
                        <option value="+420"><?php echo __('+420') ?></option>
                        <option value="+45"><?php echo __('+45') ?></option>
                        <option value="+372"><?php echo __('+372') ?></option>
                        <option value="+358"><?php echo __('+358') ?></option>
                        <option value="+33"><?php echo __('+33') ?></option>
                        <option value="+49"><?php echo __('+49') ?></option>
                        <option value="+30"><?php echo __('+30') ?></option>
                        <option value="+852"><?php echo __('+852') ?></option>
                        <option value="+36"><?php echo __('+36') ?></option>
                        <option value="+91"><?php echo __('+91') ?></option>
                        <option value="+62"><?php echo __('+62') ?></option>
                        <option value="+353"><?php echo __('+353') ?></option>
                        <option value="+39"><?php echo __('+39') ?></option>
                        <option value="+962"><?php echo __('+962') ?></option>
                        <option value="+965"><?php echo __('+965') ?></option>
                        <option value="+371"><?php echo __('+371') ?></option>
                        <option value="+370"><?php echo __('+370') ?></option>
                        <option value="+352"><?php echo __('+352') ?></option>
                        <option value="+853"><?php echo __('+853') ?></option>
                        <option value="+60"><?php echo __('+60') ?></option>
                        <option value="+960"><?php echo __('+960') ?></option>
                        <option value="+356"><?php echo __('+356') ?></option>
                        <option value="+230"><?php echo __('+230') ?></option>
                        <option value="+377"><?php echo __('+377') ?></option>
                        <option value="+977"><?php echo __('+977') ?></option>
                        <option value="+31"><?php echo __('+31') ?></option>
                        <option value="+64"><?php echo __('+64') ?></option>
                        <option value="+47"><?php echo __('+47') ?></option>
                        <option value="+968"><?php echo __('+968') ?></option>
                        <option value="+48"><?php echo __('+48') ?></option>
                        <option value="+351"><?php echo __('+351') ?></option>
                        <option value="+974"><?php echo __('+974') ?></option>
                        <option value="+40"><?php echo __('+40') ?></option>
                        <option value="+966"><?php echo __('+966') ?></option>
                        <option value="+65"><?php echo __('+65') ?></option>
                        <option value="+421"><?php echo __('+421') ?></option>
                        <option value="+386"><?php echo __('+386') ?></option>
                        <option value="+34"><?php echo __('+34') ?></option>
                        <option value="+46"><?php echo __('+46') ?></option>
                        <option value="+41"><?php echo __('+41') ?></option>
                        <option value="+66"><?php echo __('+66') ?></option>
                        <option value="+971"><?php echo __('+971') ?></option>
                        <option value="+44"><?php echo __('+44') ?></option>
                        <option value="+379"><?php echo __('+379') ?></option>
                     </select>
                        <input type="text" value="" id="forgotmob" class="mobnumber"/>
                        <input type="hidden" value="<?php echo $block->getUrl("sms/index/ajaxforgot"); ?>" class="forgot-otp-url" />
                     </div>
                     </div>
                     
                    <div class="model-bottom"> 
                        <div class="submitbtnajax">
                            <input type="button" class="forgotsendotp button primary action" value="Send Otp" />
                        </div>
                        <div class="progress-indicator">
                             <span class="please-wait" id="forgot-sms-please-wait" style="display:none;">
                                 <img src="<?php echo 
							$block->getViewFileUrl('Elsnertech_Sms::images/ajax-loader.gif');?>" class="v-middle" alt=""/>
                            </span>
                        </div>
                    </div>
                   
             </div>
             <div class="forgototpverify" style="display:none">
             	 <div class="checkforgototperror" style="display:none">
                	<span class="error"><?php echo __("Incorect OTP, Please Verify Again.");?></span>
                </div>	
                <div class="blankerror error" style="display:none">
                     	<span><?php echo __("Required fields cannot be empty");?></span>
                 </div>
                 <div class="page-title">
                    <span><?php echo __('OTP Verification') ?></span>
                </div>
				<div class="otp-content">
                 <div class="input-box">
                 <label for="forgototp" class="required"><em>*</em><?php echo __('One Time Secure Password') ?></label>
                	<input type="text" value="" id="forgototp" class="border-input"/>
                    </div>
                    <input type="hidden" value="<?php echo $block->getUrl("sms/index/ajaxforgototpverify"); ?>" class="forgotcheckotpurl" />
                     
                </div>
                 <div class="model-bottom"> 
                    <div class="submitbtnajax">
                        <input type="button" class="forgotverifyotp button primary action" value="Verify OTP" />
                    </div>
                    <div class="progress-indicator">
                             <span class="please-wait" id="forgot-sms-verify-please-wait" style="display:none;">
                                <img src="<?php echo 
							$block->getViewFileUrl('Elsnertech_Sms::images/ajax-loader.gif');?>" class="v-middle" alt=""/>
                            </span>
                    </div>
                </div>
               
            </div>
             <div class="setnewpass" style="display:none">
             	<div class="passmatcherror error" style="display:none">
                	<span><?php echo __("Password doesn't Match.");?></span>
                </div>
                <div class="resetpassvalidation error" style="display:none">
                	<span><?php echo __("Password should be more then 6 character.");?></span>
                </div>
				<div class="blankerror error" style="display:none">
                     	<span><?php echo __("Required fields cannot be empty");?></span>
                 </div>
             	 <div class="page-title">
                    <span><?php echo __('Reset your Password') ?></span>
                </div>
				<div class="otp-content">
                	<div class="newpass reginput odd ">
                            <label for="newpassotp" class="required"><em>*</em><?php echo __('New Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="newpass" value="" id="newpassotp" class="input-text required-entry border-input" title="<?php echo __('New password') ?>" />
                            </div>
                      </div>
                      <div class="confirmpass reginput odd ">
                            <label for="newpassconrm" class="required"><em>*</em><?php echo __('Confirm Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="newpassconrmotp" value="" id="newpassconrmotp" class="input-text required-entry border-input" title="<?php echo __('Confrim Password') ?>" />
                            </div>
                        </div>
                    <input type="hidden" value="<?php echo $block->getUrl("sms/index/ajaxupdatepassotp"); ?>" class="updatepassotp" />
                  
                     
                </div>
                 <div class="model-bottom">
                    <div class="submitbtnajax">
                        <input type="button" class="updatepassbtn button primary action" value="Submit" />
                    </div>
                    <div class="progress-indicator">
                                 <span class="please-wait" id="set-new-pass-please-wait" style="display:none;">
                                    <img src="<?php echo 
							$block->getViewFileUrl('Elsnertech_Sms::images/ajax-loader.gif');?>" class="v-middle" alt=""/>
                                </span>
                     </div>
                </div>
             </div>
             <input type="checkbox" name="forgotwithemail"> <?= __("Forgot with Email"); ?>
    	</div>

            <div id="ajaxforgot-forgot-window" class="forgot-window account-forgot ajaxforgotphtml no-display">
                <form action="<?php echo $block->getUrl('sms/index/ajaxemailforgot') ?>" method="post" id="email-forgot-form" class="scaffold-form">
                    <?php echo $block->getBlockHtml('formkey'); ?>
                    <div class="forgotemailerror error" style="display:none">
                     	<span><?php echo __("We're unable to send the password reset email PLEASE CONTACT TO STORE ONWER.");?></span>
                     </div>
                     <div class="forgotemailsuccess success" style="display:none">
                     	<span><?php echo __("If there is an account associated with email Address you will receive an email with a link to reset your password");?></span>
                     </div>
                     <div class="forgotemailrequird success" style="display:none">
                     	<span><?php echo __("Please Enter Email");?></span>
                     </div>
                    <div class="content">
                                <label for="email" class="required"><em>*</em><?php echo __('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="login[email]" value="" id="email-forgot" class="input-text required-entry border-input" title="<?php echo __('Email Address') ?>" />
                                </div>
                    </div>
                    <div class="buttons-set">
                        <div class="loginlink">
                            <button type="submit" class="button primary action" title="<?php echo __('Submit') ?>" name="send" id="forgotsubmit"><span><span><?php echo __('Submit') ?></span></span></button>
                        </div>
                    </div>
                </form>
            </div>
    </div>
  </div>

</div>
