<?php
/**
 * @category Mageants GiftCard
 * @package Mageants_GiftCard
 * @copyright Copyright (c) 2016 Mageants
 * @author Mageants Team <support@mageants.com>
 */
if (!$block->isCartEmpty()):
    ?>    
        <a href="javascript:void(0)" id="gift-code"><?= /* @noEscape */
        __('Apply Gift Card  '); ?><i class="fa fa-angle-down" id="gift-code-arrow">
        </i></a>
        <input type="hidden" id="base-gift-url" value="<?= /* @noEscape */
        $block->getUrl(); ?>"/>
        <div class="gift-code-block">
            <form id="gift-certificate-form" method="post">                
            <?php if ($block->getGiftCardCode() != "") { ?>                    
                    <input class="input-text gift-certificate-code" id="gift-certificate-code"
                     name="gift_certificate_code" placeholder="Enter Gift Card Code"
                      type="text" value="<?= /* @noEscape */ $block->getGiftCardCode(); ?>"
                       readonly>
                    <button class="action apply-certificate primary" id="applyCode" type=
                    "submit" ><span>Cancel</span></button>
                <?php	} else { ?>
                    <input class="input-text gift-certificate-code" id="gift-certificate-code"
                     name="gift_certificate_code" value="" placeholder=
                     "Enter Gift Card Code" type="text" required>
                    <button class="action apply-certificate primary" id="applyCode" type=
                    "submit" ><span>Apply</span></button>
                <?php } ?>                
                <button class="action apply-certificate primary" type="button" id=
                "check_status"><span>Check Status</span></button>
                <div class="loading"></div>
            </form>    
            <div id="message"> <span class="error-msg"><?= /* @noEscape */ __("Enter Gift
            Card"); ?></span></div>
        <?php if ($block->getGiftCardCode() != "") { ?>                    
            <div class="apply-certificate"> <span style="color:#006400"><?= /* @noEscape */
            __("Gift Card Accepted"); ?></span></div>
            <?php } ?>
            <div > <span style="color:#f00"><?= /* @noEscape */ __("Note: Gift Card
            cannot be used to buy  gift card"); ?></span></div>
        </div>

        <script>
            require(['jquery','giftcertificate'],function($){
            });
        </script>
    <?php
    endif;
