<div class="container">
    <div class="bgimg">
      <div class="topleft"></div>
      <div class="middle">
        <h1>COMING BACK SOON! We are doing improvements for better Experience!</h1>
        <div style="font-size: 15px;">------------XXXXXXXXXXXX------------</div>
    	<p>For order and product enquiries: <a href="https://wa.me/918866799113?text=Hi%20saree.com%20Stylist%20!">Whatsapp us</p>
      </div>
      <div class="bottomleft"></div>
    </div>
</div>

</body>
</html>
<style>
html { 
			background: url(images/maintenancebg.jpg) no-repeat center center fixed; 
			-webkit-background-size: cover;
			-moz-background-size: cover;
			-o-background-size: cover;
			background-size: cover;
		}

.page-main {
    padding: 0;
}
.bgimg {
  height: 100%;
  color: white;
  letter-spacing: 3px !important;
  text-transform: uppercase !important;
  font-size:22px !important;
  }

.topleft {
  position: absolute;
  top: 0;
  left: 16px;
}

.bottomleft {
  position: absolute;
  bottom: 0;
  left: 16px;
}

.middle {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}

hr {
  margin: auto;
  width: 40%;
}

a:link {
  color: white;
}

/ visited link /
a:visited {
  color: white;
}

/ mouse over link /
a:hover {
  color: red;
}

/ selected link /
a:active {
  color: white;
} 
</style>

<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<!--<h1>Service Temporarily Unavailable</h1>-->
<!--<p>-->
<!--    The server is temporarily unable to service your request due to maintenance downtime or capacity problems.-->
<!--    Please try again later.-->
<!--</p>-->