<?php
$configs = $block->getConfigs();
$title = $configs['autocomplete']['topProducts']['title'];

$currency = $configs['store']['currency']['symbol'];
?>

<script type="text/template" id="wizzy-autocomplete-topproducts">

    <div class="wizzy-autocomplete-top-products">
        <?php
        if ($title != "") {
            ?>
           <p class="top-products-title"><?= $block->escapeHtmlAttr($title) ?></p>
            <?php
        }
        ?>
        <ul class="autocomplete-top-products">
            {{#products}}

                <li class="topproduct-item" title="{{{ name }}}">
                    <a href="{{{url}}}" class="topproduct-item-link">
                        <div class="topproduct-item-image">
                            <img src="{{ mainImage }}" class="topproduct-image" />
                        </div><!-- ending of topproduct-item-image -->
                        <div class="topproduct-item-info">
				<? /*<strong class="product name product-item-name">{{{ brand }}} </strong> */ ?>
                                                    <p class="topproduct-title">{{{ name }}}</p>
                            <p class="topproduct-price">
                                <?= $block->escapeHtmlAttr($currency); ?>{{ sellingPrice }} {{#price}}
                                <span class="topproduct-original-price">
                                    <?= $block->escapeHtmlAttr($currency); ?>{{ price }}
                                </span>
                                {{/price}}
                                <? /* <span class="topproduct-item-discount">
                                   {{#discountPercentage}}
                                       ({{discountPercentage}}% off)
                                   {{/discountPercentage}}
                               </span></p> */ ?>

				<? /*<span class="product-item-link"> {{{ sku }}} </span> */ ?>
                        </div><!-- ending of topproduct-item-info -->
                    </a><!-- ending of topproduct-item-link -->
                </li><!-- ending of topproduct-item -->

            {{/products}}
        </ul><!-- ending of autocomplete-top-products -->
    </div><!-- ending of top-products -->

</script>
