<?php /* @var \Magento\Directory\Block\Currency $block */ ?>
    <?php if ($block->getCurrencyCount() > 1): ?>
        <?php $currencies = $block->getCurrencies(); ?>
        <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
        <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
        <?php
            $currentCurrencyCodeHtml = $currentCurrencyCode;
            if (!$block->getVar('compact_currency_switcher/enabled', 'Argento_Theme')) {
                $currentCurrencyLabel = $currencies[$currentCurrencyCode] ?: '';
                $currentCurrencyCodeHtml .= ' - ' . $currentCurrencyLabel;
            }
        ?>
        <div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
            <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Currency')) ?></span></strong>
            <div class="actions dropdown options switcher-options">
                <div class="action toggle switcher-trigger"
                    id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
                    data-mage-init='{"dropdown":{}}'
                    data-toggle="dropdown"
                    data-trigger-keypress-button="true">
                    <strong class="language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                        <span><?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?></span>
                    </strong>
                </div>
                <ul class="dropdown switcher-dropdown" data-target="dropdown">
                    <?php foreach ($currencies as $_code => $_name): ?>
                        <?php if ($_code != $currentCurrencyCode): ?>
                            <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                                <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><?= $block->escapeHtml($_code) ?> </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>