<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$blockObj= $block->getLayout()->createBlock('Logicrays\Customization\Block\Customization');

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<li class="cart-item">
    <?php if ($block->hasProductUrl()) :?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
    <?php else :?>
        <span class="product-item-photo">
    <?php endif;?>
    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
    <?php if ($block->hasProductUrl()) :?>
        </a>
    <?php else :?>
        </span>
    <?php endif; ?>
    <div class="product-item-details">
        <div class="product-item-top-info">
            <div class="cart-name-qty">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else :?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                
                <div class="field qty">
                    <div class="control qty">
                        <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                            <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                            <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                   name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                   data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                   value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                   type="number"
                                   size="4"
                                   step="any"
                                   title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                   class="input-text qty"
                                   data-validate="{required:true,'validate-greater-than-zero':true}"
                                   data-role="cart-item-qty"/>
                        </label>
                    </div>
                </div>
            </div>
            
            <div class="cart-subtotal-price">
                <?php 
                   $discount = 0;
                    if($_item->getPrice() != $_item->getProduct()->getPrice()){
                        $discount = $blockObj->getRowItemDiscount($_item->getPrice(),$_item->getProduct()->getPrice(),$_item->getStore());
                        $currencySymbol = $blockObj->getCurrentCurrencySymbol();
                        $discountAmount = $discount * $_item->getQty();
                    }
                if($discount > 0): ?>
                    <script>
                        if(window.checkoutConfig != undefined){
                            window.checkoutConfig.quoteItemData.forEach(function(item,index,array){
                                if(<?= $_item->getId() ?> == item['item_id']){
                                    window.checkoutConfig.quoteItemData[index]['rowDiscount'] = <?= $block->escapeHtml($discountAmount); ?>;
                                }
                            });
                        }
                    </script>
                    <script>
                        require([
                            'jquery',
                        ],  
                        function ($) {
                            if(window.checkoutConfig != undefined){
                                window.checkoutConfig.quoteItemData.forEach(function(item,index,array){
                                    if(<?= $_item->getId() ?> == item['item_id']){
                                        window.checkoutConfig.quoteItemData[index]['rowDiscountNew'] = <?= $block->escapeHtml($discountAmount); ?>;
                                    }
                                });
                            }
                        });
                    </script>
                <?php endif
                ?>
                
                <?php if ($canApplyMsrp) :?>
                    <span class="cart msrp subtotal">--</span>
                <?php else :?>
                    <?= $block->getRowTotalHtml($_item) ?>
                    <?php if($discountAmount > 0): 
                           $original= $_item->getProduct()->getPrice();
                           $current = $_item->getProduct()->getSpecialPrice();
                           $diff = $current - $original;
                           $diff = abs($diff);
                           $percentChange = ($diff/$original)*100;
                           $original = number_format($original*$_item->getQty(),2)."  ";
                        ?>
                        <span   style="font-size: initial;"><b><del> <?= $block->escapeHtml("  ".$currencySymbol.$original); ?></del><span style="color:#c22025c9"><?= $block->escapeHtml(number_format($percentChange,2)."%off"); ?></span></b></span>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        
        
        <div class="product-item-cart-bottom">
            <div class="product-option-info">
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
            
                            
                            </dd>
                        <?php endforeach; ?>
                        <?php 
                           $discount = 0;
                            if($_item->getPrice() != $_item->getProduct()->getPrice()){
                                $discount = $blockObj->getRowItemDiscount($_item->getPrice(),$_item->getProduct()->getPrice(),$_item->getStore());
                                $currencySymbol = $blockObj->getCurrentCurrencySymbol();
                                $discountAmount = $discount * $_item->getQty();
                            }
                        if($discount > 0): ?>
                            <script>
                                if(window.checkoutConfig != undefined){
                                    window.checkoutConfig.quoteItemData.forEach(function(item,index,array){
                                        if(<?= $_item->getId() ?> == item['item_id']){
                                            window.checkoutConfig.quoteItemData[index]['rowDiscount'] = <?= $block->escapeHtml($discountAmount); ?>;
                                        }
                                    });
                                }
                            </script>
                            <script>
                                require([
                                    'jquery',
                                ],  
                                function ($) {
                                    if(window.checkoutConfig != undefined){
                                        window.checkoutConfig.quoteItemData.forEach(function(item,index,array){
                                            if(<?= $_item->getId() ?> == item['item_id']){
                                                window.checkoutConfig.quoteItemData[index]['rowDiscountNew'] = <?= $block->escapeHtml($discountAmount); ?>;
                                            }
                                        });
                                    }
                                });
                            </script>
                        <?php endif
                        ?>
                            
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) :?>
                    <?php foreach ($messages as $message) :?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </div>
    </div>
</li>
