<?php
/**
 *@var Logicrays\OrderCancellation\Block\CancelOrder $block
 **/
    $orderId = $block->getOrderNumber();
    $order_status = $block->getOrderStatus();
?>
<?php
  $modEnable = $block->modEnable();
  $day = $block->getDateForComplete();
  $hours = $block->getHourDiffAfterPlace();
  $date_diff = "no_date";
  if(!empty($day)){
      $o_date = $day[0]['created_at'];
      $order_date = strtok($o_date, ' ');
      $now = time();
      $updated_order_date = strtotime($order_date);
      $datediff = $now - $updated_order_date;
      $date_diff = $datediff / (60 * 60 * 24);
  }
  if($order_status == "request_for_cancellation"){?>
    <b> <?php echo "Your cancellation request has been successfully submitted. Please allow 48 hours for it to be processed and approved."; ?></b>
  <?php }
  if($order_status != 'canceled' && $order_status != 'request_for_cancellation' && ($date_diff != 'no_date' || $hours) && $date_diff < 2 && $modEnable == 1){
?>
<a href = "<?= $block->getUrl('cancelorder/customer/index/order_id/'.$orderId); ?>" class="action primary add">
    <?php
        echo $block->getLinkText();
    }
    ?>
</a>