<?php
   $url = $block->getAssetUrl('Logicrays_OrderCancellation::css/style.css');
   if ($url):
       echo '<link href="'.$url.'" rel="stylesheet" type="text/css" media="all" />';
   endif;
   ?>
<head>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
   <script>
      require(['jquery', 'myscript'], function($, myscript) {
          myscript();
      });
   </script>
</head>
<div class="previous">
   <a href="<?= $this->getUrl('sales/order/view/order_id/'.$block->getOrderNumber()); ?>">Back To Previous Page</a>
</div>
<div class="cancel-order-title">
   <h3>
      Order # <?php echo $block->getOrder(); ?>
   </h3>
</div>
<div class="order-cancel-table">
   <div class="table">
      <form class="tr" enctype='multipart/form-data' method="post" id="myform" action="<?php echo $this->getUrl('cancelorder/index/cancelorderprocess') ?>">
         <div class="select_cancellation_option">
            <label><b>Please Select Cancellation Option :</b></label>
            <select name="order_cancellation_option" id="order_cancellation_option" required>
               <option value="">Please Select...</option>
               <option value="cancel_entire_order">Cancel Entire Order</option>
               <option value="specific_item">Selected Items Only</option>
            </select>
         </div>
         <div class="items data-order-cancel">
            <h5><strong>Items Ordered</strong></h5>
            <div class="order-cancel-data-table">
               <table class="data table table-order-items">
                  <tr>
                     <th>Product Name</th>
                     <th>SKU</th>
                     <th>Price</th>
                     <th class="select_item">#</th>
                     <th class="select_item">Ordered Qty</th>
                     <th class="select_item">For Cancel Qty</th>
                     <th></th>
                     <th class="select_item">Cancellation Reason</th>
                  </tr>
                  <?php
                     $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                     $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                     $reasons = $block->getReasons();
                    //  print_r($reasons);die;
                     foreach($block->getOrderItem() as $item)
                     {
                        // print_r(get_class_methods($item));
                        // print_r();die;
                       if($item->getCancelRequest()== 0.0000){
                         $class = 'selectable';
                       }
                       else {
                         $class = 'unselectable';
                       }
                       $o_date = $block->getOrderCreateDate();
                       $o_time = substr($o_date, strpos($o_date, " ") + 1);
                       $order_time_hours = strtok($o_time, ':');
                       $order_date = strtok($o_date, ' ');
                     ?>
                  <span class="td"><input type="hidden" name="order_id" value=<?= $block->getOrderNumber(); ?>></span>
                  <span class="td"><input type="hidden" name="item_id" value=<?= $item->getItemId(); ?>></span>
                  <span class="td"><input type="hidden" name="order_date" id= "order_date" value=<?= $order_date; ?>></span>
                  <span class="td"><input type="hidden" name="order_time" id= "order_time" value=<?= $order_time_hours; ?>></span>
                  <tr class='<?= $class; ?>' id='tbl_row'>
                     <td class="col name">
                        <?= $item->getName(); ?>
                     </td>
                     <td class="col sku">
                        <?= $item->getSku(); ?>
                     </td>
                     <td class="col price">
                        <?= $priceHelper->currency(($item->getPrice() * $item->getQtyOrdered()),true,false); ?>
                     </td>
                     <td class='select_item'  id="<?= $class; ?>">
                        <input type="checkbox" id="<?= $item->getItemId(); ?>" name="selected_item[]" value="<?= $item->getItemId(); ?>" >
                     </td>
                     <td class='select_item'  id="<?= $class; ?>">
                        <input type="number" id="total_ordered_qty" name=<?php echo "total_ordered_qty".$item->getItemId()?> value="<?=  number_format($item->getQtyOrdered(),0); ?>" disabled>
                     </td>
                     <td class='select_item'  id="<?= $class; ?>">
                        <input type="number" id="item_cancellation_qty" name=<?php echo "item_cancellation_qty_".$item->getItemId()?> placeholder="Enter Cancel Qty" value="<?= number_format($item->getCancelRequest(),0); ?>" max="<?=  number_format($item->getQtyOrdered(),0); ?>" disabled>
                     </td>
                     <td></td>
                     <td class='select_item'  id="<?= $class; ?>">
                        <select name=<?php echo "item_cancellation_reason_".$item->getItemId()?> id="item_cancellation_reason" class="item_cancellation_reason" disabled>
                           <?php foreach($reasons as $option) {?>
                           <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
                           <?php } ?>
                        </select>
                     </td>
                  </tr>
                  <?php
                     }
                     ?>
               </table>
            </div>
         </div>
         <div class="order-cancel-input">
            <div class="select_cancellation_reason" style="display:none;">
               <label><b>Please Select Reason :</b></label>
               <select name="order_cancellation_reason" id="order_cancellation_reason">
                  <?php foreach($reasons as $option) {?>
                  <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
                  <?php } ?>
               </select>
            </div>
         </div>
         <div class="order-cacel-textarea">
            <div class="cancellation_note">
               <label><b>Enter Cancellation Note Here :</b></label>
               <textarea id="order_cancellation_note" name="order_cancellation_note" rows="3" cols="30" placeholder="Enter Cancellation Note Here :"></textarea>
            </div>
         </div>
         
         <div class="order-cacel-textarea">
            <div class="cancel-image">
               <label><b>Upload image if required :</b></label>
               <input type="file" name="upload_cancelreq_file1" id="upload_cancelreq_file1" title="Cancel Request Product Image" class="input-text" >
               <input type="file" name="upload_cancelreq_file2" id="upload_cancelreq_file2" title="Cancel Request Product Image" class="input-text" >
            </div>
         </div>
         <div class="order-cacel-textarea">
            <input type="submit" id="submit" name="submit" value="submit" />
         </div>
      </form>
      <?php
         $shippingAddress = $block->getCustomerShippingAdd();
         $billingAddress = $block->getCustomerBillingAdd();
         $orderData = $block->getOrderInfo();
         $payment = $orderData->getPayment();
         $method = $payment->getMethodInstance();
         $methodTitle = $method->getTitle();
         $shippingMethod = $orderData->getShippingMethod();
         $countryName = $block->getCountryName($billingAddress->getCountryId());
         ?>
      <div class="block block-order-details-view">
         <div class="block-title">
            <strong>Order Information</strong>
         </div>
         <div class="block-content">
            <div class="box box-order-shipping-address">
               <strong class="box-title"><span>Shipping Address</span></strong>
               <div class="box-content">
                  <address>
                     <?php echo $shippingAddress->getFirstname() .' '. $shippingAddress->getLastname();?><br>
                     <?php echo $billingAddress['street']; ?><br>
                     <?php echo $shippingAddress->getCity().','; ?>
                     <?php echo $shippingAddress->getRegion().','; ?><br>
                     <?php echo $countryName.','; ?>
                     <?php echo $shippingAddress->getPostcode(); ?><br>
                     <?php echo 'T: '.$shippingAddress->getTelephone(); ?><br>
                  </address>
               </div>
            </div>
            <div class="box box-order-shipping-method">
               <strong class="box-title">
               <span>Shipping Method</span>
               </strong>
               <div class="box-content">
                  <?= $shippingMethod; ?>
               </div>
            </div>
            <div class="box box-order-billing-address">
               <strong class="box-title">
               <span>Billing Address</span>
               </strong>
               <div class="box-content">
                  <address>
                     <?php echo $billingAddress->getFirstname() .' '. $billingAddress->getLastname();?><br>
                     <?php echo $billingAddress['street']; ?><br>
                     <?php echo $billingAddress->getCity().','; ?>
                     <?php echo $billingAddress->getRegion().','; ?><br>
                     <?php echo $countryName.','; ?>
                     <?php echo $billingAddress->getPostcode(); ?><br>
                     <?php echo 'T: '.$billingAddress->getTelephone(); ?><br>
                  </address>
               </div>
            </div>
            <div class="box box-order-billing-method">
               <strong class="box-title">
               <span>Payment Method</span>
               </strong>
               <div class="box-content">
                  <dl class="payment-method checkmemo">
                     <dt class="title"><?= $methodTitle; ?></dt>
                  </dl>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>


<script>
  require([
        'jquery',
    ], function ($) {
        $(window).load(function(){
            rmOption();
        });
    });

   function rmOption() {
     var date = new Date();
     var year = date.toLocaleString("default", { year: "numeric" });
     var month = date.toLocaleString("default", { month: "2-digit" });
     var day = date.toLocaleString("default", { day: "2-digit" });
     var formattedDate = year + "-" + month + "-" + day;
     const orderdate = document.getElementById('order_date').value;
     const orderTimeHours = document.getElementById('order_time').value;
     var d = new Date();
     d.getHours();
     if (formattedDate != orderdate) {
       var dropdownOption = document.getElementById("order_cancellation_reason");
       dropdownOption.remove(1);
       var itemDropDown = document.getElementsByClassName("item_cancellation_reason");
       for (i = 0; i < itemDropDown.length; i++) {
           var itemDropDown = document.getElementsByClassName("item_cancellation_reason")[i];
           // itemDropDown.remove(1);
       }
     }
     if (formattedDate == orderdate) {
       time_diff = d.getHours() - orderTimeHours;
       if (time_diff > 2) {
         var dropdownOption = document.getElementById("order_cancellation_reason");
         dropdownOption.remove(1);
         var itemDropDown = document.getElementsByClassName("item_cancellation_reason");
         for (i = 0; i < itemDropDown.length; i++) {
             var itemDropDown = document.getElementsByClassName("item_cancellation_reason")[i];
             // itemDropDown.remove(1);
         }
       }
     }
   }
   
   require(['jquery', 'domReady!'], function ($) {
        $("#myform").on("submit", function () {
            $('body').trigger('processStart');
        });
    });
    
    $("input[type='checkbox']").on('change', function () {
        $(this).closest("tr").find("select[id=item_cancellation_reason]").prop("disabled", !this.checked);
        $(this).closest("tr").find("select[id=item_cancellation_reason]").prop("required", this.checked);
        $(this).closest("tr").find("input[id=item_cancellation_qty]").prop("disabled", !this.checked);
        $(this).closest("tr").find("input[id=item_cancellation_qty]").prop("required", this.checked)
    });
    
    $('select[name=order_cancellation_option]').change(function () {
        if ($(this).val() == 'cancel_entire_order') {
            $('#order_cancellation_reason').prop('required', true);
        } else {
            $('#order_cancellation_reason').prop('required', false);
        }
    });

    $('#submit').click(function () {
        var optionVal = document.getElementById("order_cancellation_option").value;
        if (optionVal == 'specific_item') {
            var checkboxs = document.getElementsByName("selected_item[]");
            var okay = false;
            for (var i = 0, l = checkboxs.length; i < l; i++) {
                if (checkboxs[i].checked) {
                    okay = true;
                    break;
                }
            }
            if (okay) {
                return true;
            }
            else {
                alert("Please select atleast one item");
                return false;
            }
        }
    });

    $(".select_item").hide();
    var unselectable = document.getElementsByClassName('unselectable');
    if (unselectable.length != 0) {
        var optionDropDown = document.getElementById("order_cancellation_option");
        optionDropDown.remove(1);
    }
    $('#order_cancellation_option').on('change', function () {
        var val = $(this).val();
        const element = document.getElementById("tbl_row");
        if (val == 'specific_item') {
            $(".select_item").show();
            $('.select_cancellation_reason').css("display", "none");
        }
        else {
            $(".select_item").hide();
        }
        if (val == 'cancel_entire_order') {
            $('.select_cancellation_reason').css("display", "block");
        }
    });
</script>
</body>