<?php
/**
 * @var $block \Logicrays\TermsAndCondition\Block\Adminhtml\Order\View\View
 */
?>
<div class="admin__page-section order-privacy-policy">
    <div class="admin__page-section-title">
        <span class="title">Terms and Conditions</span>
    </div>
    <div class="admin__page-section-item-content">
        <div class="order-privacy-policy-title"><?= __($block->getOrderCustom()); ?></div>
    </div>
</div>