<div id="otp-popup-content" style="display: none;">
    <form id="form-validate" autocomplete="off"
        data-mage-init='{"validation":{}}'
        data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <fieldset class="fieldset">
            <div class="field required">
                <label for="logicrays-order-otp" class="label"><span><?php echo __('Enter Otp') ?></span></label>
                <div class="control">
                    <input type="text" name="otp" id="logicrays-order-otp" value="" title="<?php echo __('Otp') ?>"
                        class="input-text" data-validate="{required:true, 'validate-number':true}">
                </div>
            </div>
            <div id="otp-messages">
                <span id="otp-error-message" style="color:crimson"></span>
            </div>
            <div class="otp-messages" style="padding-top:2%">
                <span id="otp-success-message" style="color:green"></span>
            </div>
        </fieldset>
    </form>
</div>
