<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\View\Element\Template;

/**
 * @var $block \Magento\Shipping\Block\Tracking\Popup
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$results = $block->getTrackingInfo();
$trackingIsAvailable = 0;
$orderStatus = "";
?>
    
<div class="page tracking">
    <?php if (!empty($results)): ?>
        <?php foreach ($results as $shipId => $result): ?>
            <?php if ($shipId): ?>
                <div class="order subtitle caption">
                    <?php /* @noEscape */ $block->escapeHtml(__('Shipment #')) . $shipId ?>
                </div>
            <?php endif; ?>
            <?php if (!empty($result)): ?>
                <?php foreach ($result as $counter => $track): ?>
                     <?php
                            $shipmentBlockIdentifier = $shipId . '.' . $counter;
                            if(strtolower($track['carrier']) == 'dhl'){
                                $DHLTrackingInfo = $block->getDHLTrackingInfo($track['number']); 
                                ?>


                    <div class="table-wrapper">
                         <div class="track-process">
                                <h3><?php
                                if(count($DHLTrackingInfo)){
                                    $trackingIsAvailable = 1;
                                if($DHLTrackingInfo['EventCode'] == "OK"){
                                    $orderStatus = "Delivered";
                                    echo $block->escapeHtml(__("Delivered"));
                                }
                                else{
                                    echo $block->escapeHtml(__("Out For Delivery"));
                                }
                                $block->escapeHtml(__($DHLTrackingInfo['status'])); ?></h3>
                                <p><?php echo $block->escapeHtml(__($DHLTrackingInfo['formatedDate']." ")); echo $block->escapeHtml(__($DHLTrackingInfo['localTime']." Local IST Time")); if($DHLTrackingInfo['DestinationServiceArea']) { echo $block->escapeHtml(__(", Service Area: ".$DHLTrackingInfo['DestinationServiceArea'])); }?></p>
                                <h5><?php echo $block->escapeHtml(__("Origin Service Area : ".$DHLTrackingInfo['OriginServiceArea'])); ?></h5>

                                <div class="horizontal timeline">
                                    <div class="steps">
                                        <div class="step filled step-ordered">
                                            <span class="text-img">
                                                <img src='<?php echo $this->getViewFileUrl('images/11.svg'); ?>' alt="Ordered"/>
                                                Ordered
                                            </span>
                                        </div>
                                        <div class="step filled step-dispatched">
                                            <span class="text-img">
                                                <img src='<?php echo $this->getViewFileUrl('images/12.svg'); ?>' alt="Dispatched"/>
                                                Dispatched</span>
                                        </div>
                                        <div class="step current step-out-for-delivery">
                                            <span class="text-img">
                                                <img src='<?php echo $this->getViewFileUrl('images/13.svg'); ?>' alt="Out For Delivery"/>
                                                Out For Delivery</span>
                                        </div>
                                        <div class="step step-delivered">
                                            <span class="text-img">
                                                <img src='<?php echo $this->getViewFileUrl('images/14.svg'); ?>' alt="Delivered"/>
                                                Delivered</span>
                                        </div>
                                    </div>

                                    <div class="line out-for-delivery-fill"></div>
                                </div>
                            </div>
                            
                                <div class="c-tracking-result--section">
                                    <div class="l-grid-main c-tracking-result--checkpoints-dropdown js--accordion--type-default c-accordion--item js--accordion--item l-grid l-grid--left-s is-open is-latest">
                                        <div class="l-grid-main c-accordion--hitbox js--accordion--hitbox c-component-accordion--header js--accordion--header js--dropdown-checkpoints-open l-grid ">
                                            <div id="c-tracking-result--checkpoints-dropdown-button" class=" c-tracking-result--moredetails-dropdown-button js--dropdown-moredetails-toggle-btn js-tracking-result--checkpoints--toggle-btn has-icon more-shipment-details" aria-expanded="true" aria-controls="c-tracking-result--checkpoints-dropdown-menu" style="cursor: pointer;">
                                                <h3 class="c-tracking-result--detail-label level4">More Shipment Details</h3></label>
                                            </div>
                                        </div>
                                        <div class="c-tracking-result--checkpoints-dropdown-menu c-accordion--content js--accordion--content more-shipment-details-content" id="c-tracking-result--checkpoints-dropdown-menu" aria-labelledby="c-tracking-result--checkpoints-dropdown-button" style="display: block; height: auto; overflow: hidden auto;">
                                            <table>
                                                <!-- tr>
                                                    <td>To protect your privacy, more delivery details are available after validation</td><td><?= $block->escapeHtml(__($DHLTrackingInfo['moreShippmentDetail']));?></td>
                                                </tr> -->
                                                <tr>
                                                    <td>Piece ID</td><td><?= $block->escapeHtml(__($DHLTrackingInfo['pieceId']));?></td>
                                                </tr>
                                                <tr>
                                                    <td>Waybill Number</td><td><?= $block->escapeHtml(__($DHLTrackingInfo['waybillNumber']));?></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                                <div class="c-tracking-result--section">

                                    <div class="l-grid-main c-tracking-result--checkpoints-dropdown js--accordion--type-default c-accordion--item js--accordion--item l-grid l-grid--left-s is-open is-latest">
                                        <div class="l-grid-main c-accordion--hitbox js--accordion--hitbox c-component-accordion--header js--accordion--header js--dropdown-checkpoints-open l-grid ">
                                            <div id="c-tracking-result--checkpoints-dropdown-button" class="c-tracking-result--moredetails-dropdown-button js--dropdown-moredetails-toggle-btn js-tracking-result--checkpoints--toggle-btn has-icon" aria-expanded="true" aria-controls="c-tracking-result--checkpoints-dropdown-menu">
                                                  <section class="accordion">
                                                    <div class="tab">
                                                        <input type="checkbox" name="accordion-1" id="cb1" checked>
                                                        <label for="cb1" class="tab__label all-shipment-updates"><h3 class="c-tracking-result--detail-label level4 all-shipment-updates" style="cursor: pointer;">All Shipment Updates</h3></label>
                                                    </div>
                                                </section>

                                            </div>
                                            </div>
                                        </div>
                                        <div class="c-tracking-result--checkpoints-dropdown-menu c-accordion--content js--accordion--content all-shipment-updates-content" id="c-tracking-result--checkpoints-dropdown-menu" aria-labelledby="c-tracking-result--checkpoints-dropdown-button" style="display: block; height: auto; overflow: hidden auto;">

                                            <?php
                                            $currentDate = "";
                                            $currentDateDiv = "";
                                            foreach ($DHLTrackingInfo as $key => $value) {

                                                if(is_array($value)){

                                            ?>

                                                <?php if($currentDateDiv != $value['formatedDate']){ ?>
                                                    <div class="c-tracking-result--checkpoint l-grid  l-grid--left-s main-date">
                                                        <?php $currentDateDiv = $value['formatedDate']; ?>
                                                <?php }else{ ?>
                                                    <div class="c-tracking-result--checkpoint l-grid  l-grid--left-s">
                                                <?php } ?>
                                                


                                                        <ul style="padding-top: 0px;margin-top: 0px;margin-bottom: 0px;">
                                                            <li class="l-grid">
                                                                <div class="c-tracking-result--checkpoint-left">
                                                                    <?php if($currentDate != $value['formatedDate']){
                                                                        $currentDate = $value['formatedDate'];
                                                                        ?>
                                                                        <span class="c-tracking-result--checkpoint-day"><?= $block->escapeHtml(__($value['dayName'])); ?></span>
                                                                        <span class="c-tracking-result--checkpoint-date level4" dir="ltr"><?= $block->escapeHtml(__($value['formatedDate'])); ?></span>
                                                                    <?php } ?>
                                                                    <span class="c-tracking-result--checkpoint-time" dir="ltr">
                                                                    <?= $block->escapeHtml(__($value['localTime'])); ?> Local IST Time
                                                                    </span>
                                                                </div>
                                                                <div class="c-tracking-result--checkpoint-right has-icon" style="border-left: 2px solid #bababa;">
                                                                    <span class="c-tracking-result--checkpoint--more">
                                                                            <?php if(isset($value['description'])):
                                                                                echo $block->escapeHtml(__($value['description']));
                                                                            endif; ?>
                                                                            <br>
                                                                            <?= $block->escapeHtml(__("Service Area: ".$value['serviceDescription'])); ?>
                                                                    </span>
                                                                        <div class="c-tracking-result-pieceid l-grid--w-100pc-s l-grid">
                                                                            <span class="c-tracking-result-pieceid--header c-tracking-result-pieceid--header-text">1 Piece ID: </span>
                                                                            <span class="c-tracking-result-pieceid--content is-open" aria-hidden="true">
                                                                                    <span aria-label="J D 0 1 4 6 0 0 0 1 1 4 8 3 0 6 6 8 4 9" class="js--tracking-result--pieceid link link-red" data-type="PieceId"><b><?= $block->escapeHtml(__($DHLTrackingInfo['pieceId'])); ?></b></span>
                                                                            </span>
                                                                        </div>
                                                                </div>

                                                            </li>
                                                        </ul>

                                                </div>
                                            <?php }} ?>
                                        </div>
                                    </div>
                                </div>

                                <?php
                                }
                            }
                            if(!$trackingIsAvailable){
                                $block->addChild('shipping.tracking.details.' . $shipmentBlockIdentifier, Template::class, [
                                    'track' => $track,
                                    'template' => 'Magento_Shipping::tracking/details.phtml',
                                    'storeSupportEmail' => $block->getStoreSupportEmail()
                                ]);
                            }
                        ?>
                        <?= /* @noEscape */ $block->getChildHtml('shipping.tracking.details.' .
                            $shipmentBlockIdentifier) ?>
                    </div>
                    <?php if (is_object($track) && !empty($track->getProgressdetail())): ?>
                        <?php
                            $block->addChild(
                                'shipping.tracking.progress.' . $shipmentBlockIdentifier,
                                Template::class,
                                ['track' => $track, 'template' => 'Magento_Shipping::tracking/progress.phtml']
                            );
                        ?>
                        <?= /* @noEscape */ $block->getChildHtml('shipping.tracking.progress.' .
                            $shipmentBlockIdentifier) ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="message info empty">
                    <div><?= $block->escapeHtml(__('There is no tracking available for this shipment.')) ?></div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="message info empty">
            <div><?= $block->escapeHtml(__('There is no tracking available.')) ?></div>
        </div>
    <?php endif; ?>
    <div class="actions">
        <button type="button"
                title="<?= $block->escapeHtml(__('Close Window')) ?>"
                class="action close">
            <span><?= $block->escapeHtml(__('Close Window')) ?></span>
        </button>
        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
            'onclick',
            "window.close(); window.opener.focus();",
            'button.action.close'
        ) ?>
    </div>
</div>
<?php $scriptString = <<<script

    require([
        'jquery'
    ], function (jQuery) {
        /* hide the close button when the content doesn't open in a modal window */
        if (window.opener === null || typeof window.opener === "undefined") {
            jQuery('.actions button.close').hide();
        }
        // jQuery(".more-shipment-details").click(function(){
        //     if(jQuery(".more-shipment-details-content").is(":hidden")){
        //         jQuery(".more-shipment-details-content").show();
        //     }else{
        //         jQuery(".more-shipment-details-content").hide();
        //     }
        // });
        jQuery(".all-shipment-updates").click(function(){
            if(jQuery(".all-shipment-updates-content").is(":hidden")){
                jQuery(".all-shipment-updates-content").show();
            }else{
                jQuery(".all-shipment-updates-content").hide();
            }
        });
        
        jQuery('.accordion').each(function () {
            var jQueryaccordian = jQuery(this);
            jQueryaccordian.find('.accordion-head').on('click', function () {
                jQuery(this).removeClass('open').addClass('close');
                jQueryaccordian.find('.accordion-body').slideUp();
                if (!jQuery(this).next().is(':visible')) {
                    jQuery(this).removeClass('close').addClass('open');
                    jQuery(this).next().slideDown();
                }
            });
        });
        if("$orderStatus" == "Delivered"){
            jQuery(".line").addClass('dlivered-fill');
            jQuery(".step-delivered").addClass('current');
        }
    });

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>


<style type="text/css">
 .track-process {
                            margin: 20px 0;
                        }

                        .track-process h3 {
                            font-size: 22px;
                            margin-bottom: 15px;
                        }

                        .track-process p {
                            font-size: 16px;
                            margin-bottom: 15px;
                        }

                        .track-process h5 {
                            font-size: 16px;
                            margin-bottom: 15px;
                            font-weight: 600;
                        }

                        .horizontal.timeline {
                            display: flex;
                            position: relative;
                            flex-direction: row;
                            justify-content: space-between;
                            align-items: center;
                            width: 100%;
                            margin: 75px 0 40px 0;
                            max-width: 95%;
                            margin-left: 20px;
                        }

                        .horizontal.timeline:before {
                            content: "";
                            display: block;
                            position: absolute;
                            width: 100%;
                            height: 0.2em;
                            background-color: #f2f2f2;
                        }

                        .horizontal.timeline .line {
                            display: block;
                            position: absolute;
                           
                            height: 0.2em;
                            background-color: #098203;
                        }

                        .horizontal.timeline .steps {
                            display: flex;
                            position: relative;
                            flex-direction: row;
                            justify-content: space-between;
                            align-items: center;
                            width: 100%;
                        }

                        .horizontal.timeline .steps .step.filled,
                        .horizontal.timeline .steps .step.current {
                            color: #098203;
                        }

                        .horizontal.timeline .steps .step {
                            display: block;
                            position: relative;
                            bottom: calc(100% + 1em);
                            padding: 0.33em;
                            margin: 0 2em;
                            box-sizing: content-box;
                            color: #d5d5d5;
                            background-color: currentColor;
                            border: 0.25em solid white;
                            border-radius: 50%;
                            z-index: 500;
                        }

                        .horizontal.timeline .steps .step:first-child {
                            margin-left: 0;
                        }

                        .horizontal.timeline .steps .step:last-child {
                            margin-right: 0;

                        }

                        .horizontal.timeline .steps .step span {
                            position: absolute;
                            top: calc(100% + 1em);
                            left: 50%;
                            transform: translateX(-50%);
                            white-space: nowrap;
                            color: #000;
                            opacity: 0.4;
                        }

                        .text-img {
                            opacity: 1 !important;
                            color: #000;
                            font-weight: 600;
                        }

                        .text-img img {
                            position: absolute;
                            top: -78px;
                            width: 40px;
                            left: 0;
                            right: 0;
                            margin: 0 auto;

                        }
                        .table-wrapper {
                            border: 2px solid #5d5b5b;
                            margin-top: 15px;
                            padding: 30px 80px;
                            border-radius: 5px;
                        }

                        .c-tracking-result--checkpoint ul {
                            padding-left: 0;
                        }

                        .c-tracking-result--moredetails-dropdown-button {
                            text-align: left;
                            background-color: transparent;
                            border: 1px solid #d5d5d5;
                            margin-top: 8px;
                            padding: 15px 0px;
                            border-left: 0;
                            border-right: 0;
                            border-radius: 0;
                        }

                        .c-tracking-result--moredetails-dropdown-button h3 {
                            text-align: left;
                            color: #000;
                            font-size: 18px;
                            margin: 0;
                            font-weight: 500;
                        }

                        .shipping-tracking-popup .page-main {
                            max-width: 60%;
                            margin: 0 auto;
                        }

                        div#c-tracking-result--checkpoints-dropdown-menu {
                            padding: 20px 0;
                        }

                        .l-grid-main {
                            flex-direction: column;
                        }

                        .l-grid {
                            display: flex;
                            flex: 0 1 auto;
                            margin-bottom: 0px;
                            /*flex-flow: row wrap;*/

                        }

                        .l-grid .c-tracking-result--checkpoint-right {
                            position: relative;
                        }

                        .l-grid .c-tracking-result--checkpoint-right:before {
                            content: "";
                            position: absolute;
                            height: 10px;
                            width: 10px;
                            background-color: #bababa;
                            border-radius: 50px;
                            left: -6px;
                        }

                        .main-date {
                            border-top: 1px solid #d5d5d5;
                        }

                        .main-date:first-of-type {
                            border-top: 0
                        }

                        .main-date:first-of-type .c-tracking-result--checkpoint-left,
                        .main-date:first-of-type .c-tracking-result--checkpoint-right {
                            padding-top: 0px;
                        }

                        .main-date:first-of-type .l-grid .c-tracking-result--checkpoint-right:before {
                            content: "";
                            position: absolute;
                            height: 30px;
                            width: 30px;
                            background-color: #137305;
                            border-radius: 50px;
                            left: -15px;
                            top: 0
                        }

                        .main-date:first-of-type .l-grid .c-tracking-result--checkpoint-right:after {
                            content: "";
                            display: block;
                            position: absolute;
                            top: 6px;
                            left: -4px;
                            width: 5px;
                            height: 12px;
                            border-style: solid;
                            border-color: rgb(255, 255, 255);
                            border-image: initial;
                            border-width: 0px 2px 2px 0px;
                            transform: rotate(45deg);
                        }

                        .main-date .c-tracking-result--checkpoint-left,
                        .main-date .c-tracking-result--checkpoint-right {
                            padding-top: 10px;
                        }

                        .c-tracking-result--checkpoint-day {
                            margin-bottom: 3px;
                        }

                        .c-tracking-result--checkpoint-left {
                            flex-shrink: 0;
                            width: 22.4rem;
                        }

                        .c-tracking-result--checkpoint-info span {
                            line-height: var(--size-line-height-xl);
                        }

                        .c-tracking-result--checkpoint-date {
                            display: block;
                            font-size: var(--size-font-lg);
                            margin-bottom: 0.7rem;
                        }

                        .level4,
                        .level5,
                        h4,
                        h5 {
                            line-height: var(--size-line-height-xl);
                        }

                        .level1,
                        .level2,
                        .level3,
                        .level4,
                        .level5,
                        .level6,
                        h1,
                        h2,
                        h3,
                        h4,
                        h5 {
                            font-weight: 800;
                        }

                        .c-tracking-result--checkpoint-info .c-tracking-result--checkpoint-time {
                            display: block;
                            margin-bottom: 1.4rem;
                        }

                        .c-tracking-result--checkpoint-right {
                            padding-bottom: 1.4rem;
                            padding-left: 4.2rem;
                            position: relative;
                        }

                        .c-tracking-result--checkpoint-info li:first-child .c-tracking-result--checkpoint-mobile {
                            margin-top: 1.4rem;
                        }

                        .c-tracking-result--status-shipment-delivered .c-tracking-result--checkpoint:first-child .c-tracking-result--checkpoint-right p {
                            color: var(--color-green-550);
                        }

                        .c-tracking-result--checkpoint-right p.first {
                            padding-top: 3.5rem;
                        }

                        .c-tracking-result--checkpoint-right p {
                            line-height: var(--size-line-height-xl);
                            margin-bottom: 0;
                        }

                        .c-tracking-result--checkpoint-right {
                            flex: 1 1 auto;
                            padding-left: 7.7rem;
                        }

                        .order-fill{
                            width: 0%;
                        }
                        .dspatched-fill{
                            width: 34%;
                        }
                        .out-for-delivery-fill{
                            width: 66%;
                        }
                        .dlivered-fill{
                            width: 100%;
                        }


:root {
  --primary: #227093;
  --secondary: #ff5252;
  --background: #eee;
  --highlight: #ffda79;
  /* Theme color */
  --theme: var(--primary);
}
*, *::before, *::after {
  box-sizing: border-box;
}

/* Core styles/functionality */
.tab input {
  position: absolute;
  opacity: 0;
  z-index: -1;
}
.tab__content {
  max-height: 0;
  overflow: hidden;
  transition: all 0.35s;
}
.tab input:checked ~ .tab__content {
  max-height: 10rem;
}

/* Visual styles */

.tab__label,
.tab__close {
  display: flex;
  cursor: pointer;
}
.tab__label {
  justify-content: space-between;
  padding-right: 1rem;
}
.tab__label::after {
  content: "\276F";
  width: 1em;
  height: 1em;
  text-align: center;
  transform: rotate(90deg);
  transition: all 0.35s;
}
.tab input:checked + .tab__label::after {
  transform: rotate(270deg);
}
.tab__content p {
  margin: 0;
  padding: 1rem;
}
.tab__close {
  justify-content: flex-end;
  padding: 0.5rem 1rem;
  font-size: 0.75rem;
}
.accordion--radio {
  --theme: var(--secondary);
}

/* Arrow animation */
.tab input:not(:checked) + .tab__label:hover::after {
  animation: bounce .5s infinite;
}



</style>