<?php
$viewModel = $block->getData('view_model');
$product = $block->getCurrentProduct();
$helper = $viewModel->getHelperData();
$moduleEnable = $helper->isEnable();
?>
<?php if ($moduleEnable == 1): ?>
<div id="custom_measurement_message" style="display: none;">Cash on delivery is not available for customized outfits</div>
<div id="stitching-yes-selection" style="display: none; color:red">Need to select at least one option If you are selecting <b>Custom Size: Yes</b></div>
<div class="delivery-info">
    <span>Est Dispatch Date: </span>
    <strong><label id="delivery-estimation-date"><?= $block->escapeHtml($block->getDeliveryDay()); ?></label></strong>
</div>

<div class="shipping-date-info">
    <label id="shipping-date-msg">*Please note that this is the shipping date and not the delivery date.*</label>
</div>
<input type="hidden" id="estd-dispatch-date" name="delivery-estimation-date" value="<?= $block->escapeHtml($block->getDeliveryDay()); ?>">
<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            var days;
            function productDeliveryEstimationDate() {
                var customurl = "<?= $block->escapeHtml($block->getUrl()).'delivery/estimation/index'?>";
                var product_id = "<?= /* @noEscape */ $product->getId(); ?>";

                var selectedOption = $('.product-custom-option.admin__control-select').find(":selected").text();
                if ((selectedOption.indexOf('Days') > -1) || (selectedOption.indexOf('days') > -1) ) {
                    if ((selectedOption.indexOf('To ') > -1)) {
                        optionValue1 = selectedOption.split('To ')[1];
                        optionValue2 = optionValue1.substring(0, optionValue1.indexOf(" "));
                        days = optionValue2;
                    }
                    if ((selectedOption.indexOf('to ') > -1)) {
                        optionValue1 = selectedOption.split('to ')[1];
                        optionValue2 = optionValue1.substring(0, optionValue1.indexOf(" "));
                        days = optionValue2;
                    }
                } else {
                    days = '';
                }
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        product_id: product_id,
                        days: days,
                    },
                success: function (response) {
                    $('#delivery-estimation-date').text(response.updateEstimationDate);
                    $('#estd-dispatch-date').val(response.updateEstimationDate);
                    }
                });
            }

            /*
            Add this code into comment after add Yes Later No option
            $('.product-custom-option.admin__control-select').on('change', function() {
                if ($(this).val()) {
                    productDeliveryEstimationDate();
                } else {
                    if ($('.checkbox.product-custom-option').is(':checked')) {
                        $('#custom_measurement_message').show();
                    } else {
                        var deliveryEstimationDate = "<?= $block->escapeHtml($block->getDeliveryDay()); ?>";
                        $('#estd-dispatch-date').val(deliveryEstimationDate);
                        $('#delivery-estimation-date').text(deliveryEstimationDate);
                        $('#custom_measurement_message').hide();
                    }
                }
            });*/

            var test = undefined;

            jQuery(".radio.admin__control-radio.required.product-custom-option").on("change", (function(){
                
                var checkboxLabel = jQuery(this).next("label").children("span").text();
                productDeliveryEstimationDate();
                if(checkboxLabel.trim() == "Later" || checkboxLabel.trim() == "Yes"){
                    $('#custom_measurement_message').show();
                    if(checkboxLabel.trim() == "Yes"){
                        $('#stitching-yes-selection').show();
                    }
                    else{
                        $('#stitching-yes-selection').hide();
                    }
                    if(checkboxLabel.trim() == "Yes"){
                        jQuery('div[class=field] [type="checkbox"]').each(function(i) {
                            if(this.checked) {
                                test = this;
                            }
                            jQuery(this).trigger('click');
                        });
                    }
                }
                else{
                    var deliveryEstimationDate = "<?= $block->escapeHtml($block->getDeliveryDay()); ?>";
                    $('#estd-dispatch-date').val(deliveryEstimationDate);
                    $('#delivery-estimation-date').text(deliveryEstimationDate);
                    $('#custom_measurement_message').hide();
                }
            }));

            $('.product-options-wrapper .checkbox.admin__control-checkbox.product-custom-option[type="checkbox"]').click(function() {
                var ck_box = $('input[type="checkbox"]:checked').length;
                var count = 0;
                jQuery("input:checkbox:checked").each(function(i){
                    if(jQuery(this).val() != 'on'){
                        count = 1;
                    }
                });
                if(count == 0){
                    jQuery(this).trigger('click');
                    $('#stitching-yes-selection').show();
                    jQuery('.product-options-wrapper .checkbox.admin__control-checkbox.product-custom-option[type="checkbox"]').each(function(i){
                        if(jQuery(this).val() != 'on'){
                            count = 1;
                        }
                    });
                    jQuery(".radio.admin__control-radio.required.product-custom-option").last().trigger("click");
                    jQuery(".radio.admin__control-radio.required.product-custom-option").first().trigger("click");
                }
            });
        });
    });
</script>
<?php endif; ?>