<div id="myModalnew" class="modal ajax-login-form">
    <div class="mobile-modal-content loginwithemail">
        <div class="closediv"><span class="close">&times;</span></div>
        <div style="padding:80% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/886426066?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Reel 13_Asopalav_23Oct2023"></iframe></div>
    </div>
</div>

<style>
    .closediv {
    z-index: 9999;
    padding: 10px 12px !important;
    padding-left: 8px !important;
}
</style>