<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $aaa = $_product->getCategoryIds();
$isGiftcard = 0;
if(isset($aaa[0])){
    $categoryId = $aaa[0];
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $_objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
    if($category->getName() == "Gift Card"){
        $isGiftcard = $category->getName();
    }
}

?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <!-- <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div> -->
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
            <span class="product-wishlist-link-temp">
                <span clas="product-addto-links" data-role="add-to-links">
                    <?= $block->getBlockHtml('add-to-wishlist') ?>
                </span>
            </span>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script>
require(['jquery'], function($){
     <?php if($isGiftcard){ ?>
        $('body').addClass('categorypath-giftcard');
    <?php } ?>
    $(document).ready(function(){
        if(jQuery("body").hasClass("categorypath-giftcard")){ 
            jQuery(".codcheck-prod").css('display','none'); 
            jQuery(".widget.block.block-static-block").css('display','none');
            jQuery(".product.info.detailed").css('display','none');
            jQuery(".related_contact_div").css('display','none');
            jQuery(".action.primary.tocart").text('Buy Now');
            jQuery(".action.towishlist").css("display","none");
        }
    });
});
</script>
