<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>
<?php
    $_items = $block->getReviewsCollection()->getItems();
    $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
    $viewModel = $block->getData('viewModel');
    $mediaDirectoryPath = $block->getUrl('media/review_images');
?>
<?php if (count($_items)): ?>
<div class="block review-list" id="customer-reviews">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */ __('Customer Reviews') ?>
        </strong>
    </div>
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">
            <?php foreach ($_items as $_review): ?>
                <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                    <div class="review-title" itemprop="name"><?= $block->escapeHtml($_review->getTitle()) ?></div>
                    <?php if (count($_review->getRatingVotes())): ?>
                        <div class="review-ratings">
                            <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                    <span class="label rating-label"><span><?= $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                    <div class="rating-result" title="<?= /* @escapeNotVerified */ $_vote->getPercent() ?>%">
                                        <meta itemprop="worstRating" content="1"/>
                                        <meta itemprop="bestRating" content="100"/>
                                        <span style="width:<?= /* @escapeNotVerified */ $_vote->getPercent() ?>%">
                                            <span itemprop="ratingValue"><?= /* @escapeNotVerified */ $_vote->getPercent() ?>%</span>
                                        </span>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <div class="review-content" itemprop="description">
                        <?= nl2br($block->escapeHtml($_review->getDetail())) ?>
                    </div>
                    <div class="review-details">
                        <p class="review-author">
                            <span class="review-details-label"><?= /* @escapeNotVerified */ __('Review by') ?></span>
                            <strong class="review-details-value" itemprop="author"><?= $block->escapeHtml($_review->getNickname()) ?>
                            </strong>
                        </p>
                        <p class="review-date">
                            <span class="review-details-label"><?= /* @escapeNotVerified */ __('Posted on') ?></span>
                            <time class="review-details-value" itemprop="datePublished"
                                datetime="<?= /* @escapeNotVerified */ $block->formatDate($_review->getCreatedAt(), $format) ?>"><?= /* @escapeNotVerified */ $block->formatDate($_review->getCreatedAt(), $format) ?>
                            </time>
                        </p>
                    </div>
                    <div class="review-attachments">
                        
                        <div class="review-media-value">
                            <?php
                            $thisReviewMediaCollection = $viewModel->getReviewById($_review->getReviewId());
                            if (count($thisReviewMediaCollection)) {?>
                            <p class="review-attachments-label">Attachments</p>
                            <?php
                                foreach ($thisReviewMediaCollection as $m) {
                                    ?>
                                    <div class="image item base-image" data-role="image">
                                        <div class="product-image-wrapper">
                                            <img class="product-image" data-role="image-element"
                                            src="<?= rtrim($mediaDirectoryPath, '/') . $m->getMediaUrl(); ?>"
                                            alt="Image">
                                        </div>
                                    </div>
                                    <?php
                                }

                            } 
                            // else {
                            //     echo __('No attachment available.');
                            // }
                            ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
        <div id="review-image-modal" style="display:none;">
            <img id="review-image-lg" src=""/>
        </div>
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script>
    require(['jquery', 'myscript'], function($, myscript) {
        myscript();
    });
</script>