<?php

use Tatvic\ActionableGoogleAnalytics\Block\ActionableGoogleAnalytics;
/**
 * @var $block ActionableGoogleAnalytics
 */

if($block->isEnabled() == 0){
    return;
}

if($block->isAdminLogin() == 1){
	return;
}

list($tvc_data, $get_action) = $block->getAction();
$formField = $block->formFieldTracking_Enable();
$user = $block->isCustomerLoggedIn();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$affilaition = $storeManager->getStore()->getBaseUrl();

?>

<script>
    affiliation = "<?php echo !empty($affilaition) ? $affilaition : '';?>";
    is_enable = <?php echo !empty($block->isEnabled()) ? $block->isEnabled() : 0; ?>;
    tvc_UA_ID = "<?php echo !empty($block->getUaId()) ? $block->getUaId() : ''; ?>";
    tvc_measurement_IDGA4 = "<?php echo !empty($block->getMeasurmentIDGA4()) ? $block->getMeasurmentIDGA4() : ''; ?>";
    tvc_method = "<?php echo !empty($block->method()) ? $block->method() : ''; ?>";
    tvc_mode = "<?php echo !empty($block->mode()) ? $block->mode() : ''; ?>";
    tvc_ua_both = "<?php echo !empty($block->getUaIDBoth()) ? $block->getUaIDBoth() : ''; ?>";
    tvc_ga4_both = "<?php echo !empty($block->getMeasurmentIdBoth()) ? $block->getMeasurmentIdBoth() : ''; ?>";
    tvc_gtm = <?php echo !empty($block->getGtm()) ? $block->getGtm() : 0; ?>;
    tvc_ip = "<?php echo !empty($block->checkIP_anonymization()) ? $block->checkIP_anonymization() : ''; ?>";
    tvc_ClientIDEnable = <?php echo !empty($block->checkClientId_Enabled()) ? $block->checkClientId_Enabled() : 0; ?>;
    tvc_user_id = "<?php echo !empty($block->get_user_ID()) ? $block->get_user_ID() : ''; ?>";
    tvc_ver = "<?php echo !empty($block->getMagentoVersion()) ? $block->getMagentoVersion() : ''; ?>";
    tvc_OptOut = <?php echo !empty($block->checkOptOut_Enabled()) ? $block->checkOptOut_Enabled() : 0; ?>;
    tvc_fbPixel = <?php echo !empty($block->FBPixelEnabled()) ? $block->FBPixelEnabled() : 0; ?>;
    tvc_fbPixelID = "<?php echo !empty($block->getFbPixelID()) ? $block->getFbPixelID() : ''; ?>";
    tvc_cur = "<?php echo !empty($block->getLocalCurrency()) ? $block->getLocalCurrency() : ''; ?>";
    tvc_optimise = "<?php echo !empty($block->getOptimizeIP()) ? $block->getOptimizeIP() : ''; ?>";
    tvc_cust_session = "<?php echo !empty($block->isCustomerLoggedIn()) ? $block->isCustomerLoggedIn() : ''; ?>";
    tvc_df = <?php echo !empty($block->checkDF_enabled()) ? $block->checkDF_enabled() : 0; ?>;
    tvc_link_attr = <?php echo !empty($block->getLinkAttribution()) ? $block->getLinkAttribution() : 0 ?>;
    tvc_ads_feature = <?php echo !empty($block->getDisableAdsFeature()) ? $block->getDisableAdsFeature() : 0 ?>;

    tvc_smd = {
        'tvc_UA_ID' : tvc_UA_ID,
        'tvc_measurement_id' : tvc_measurement_IDGA4,
        'tvc_mode' : tvc_mode,
        'tvc_method' : tvc_method,
        'tvc_both_uaid' : tvc_ua_both,
        'tvc_both_ga4id' : tvc_ga4_both,
        'tvc_cur' : tvc_cur,
        'tvc_mage_version' : tvc_ver,
        'tvc_extension_version' : "3.0.0",
        'tvc_license' : "M2-AGA",
        'tvc_ip' : tvc_ip,
        'tvc_OptOut' : tvc_OptOut,
        'tvc_ClientIDEnable' : tvc_ClientIDEnable,
        'tvc_user_id' : tvc_user_id,
        'tvc_link_trribution' : tvc_link_attr,
        'tvc_disable_ads_feature': tvc_ads_feature
    };

    /**
        * Opt Out concent function Enable/Disable
        */

    if (tvc_OptOut !== 0) {
        /**
            * Set to the same value as the web property used on the site
            */
        gaProperty = tvc_UA_ID;
        // Disable tracking if the opt-out cookie exists.
        disableStr = "ga-disable-" + gaProperty;
        if (document.cookie.indexOf(disableStr + "=true") > -1) {
            window[disableStr] = true;
        }

        /**
            * Opt-out function
            */
        function gaOptout() {
            expDate = new Date;
            expDate.setMonth(expDate.getMonth() + 26);
            document.cookie = disableStr + "=true; expires=" + expDate.toGMTString() + ";path=/";
            window[disableStr] = true;
        }
    }
</script>


<?php if($block->getUaId() && $block->method() === "analytics" && $block->mode() === "universal_analytics"){ ?>
    <!--Start Google Analytics anlytics.js script add-->
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', '<?php echo $block->getUaId() ?>', 'auto');
        ga('send', 'pageview');

        if (tvc_optimise !== "") {
            ga("require", tvc_optimise);
            ga("send", "pageview");
        }

        ga("require", "ec", "ec.js");

        ga("set", "currencyCode", tvc_cur);

        if (tvc_df === 1) {
            ga("require", "displayfeatures");
        }

        if (tvc_ip === 1) {
            ga("set", "anonymizeIp", true);
        }

        if (tvc_user_id !== '') {
            ga("set", "userId", tvc_user_id);
        }


        if (tvc_ClientIDEnable === 1) {
            ga(function (tracker) {
                var tvc_clientID;
                tvc_clientID = tracker.get("clientId");
                ga("set", "dimension15", tvc_clientID);
            });
        }

    </script>
    <!--End Google Analytics JS snippet-->

<?php } ?>

<?php if($block->getUaId() && $block->method() === "gtag" && $block->mode() === "universal_analytics"){ ?>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $block->getUaId() ?>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', '<?php echo $block->getUaId() ?>',{'send_page_view' : false,'currency': tvc_cur,'non_interaction': true});

        gtag("set", {"currency": tvc_cur});

        if (tvc_user_id !== '') {
            gtag('config', '<?php echo $block->getUaId() ?>',{'user_id': tvc_user_id,'send_page_view' : false,'non_interaction': true});
        }

        if(tvc_ads_feature === 1){
            gtag('set','allow_ad_personalization_signals', false );
        }

        if(tvc_ip === 1){
            gtag('event', 'IP Anonymization', { 'anonymize_ip': true });
        }

        require(
            ['Tatvic_ActionableGoogleAnalytics/js/gtagscript','jquery'],
            function(gtag_script){
                var obj = new gtag_script();
                obj.custom_dimentions();
                obj.custom_metrics();
            }
        );
    </script>
<?php } ?>

<?php if($block->getMeasurmentIDGA4() && $block->mode() === "google_analytics_4"){ ?>

    <!-- Global site tag (gtag.js) - Google Analytics 4 -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $block->getMeasurmentIDGA4() ?>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag(){
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', '<?php echo $block->getMeasurmentIDGA4() ?>',{'send_page_view' : false,'non_interaction': true});

        if (tvc_user_id !== '') {
            gtag('config', '<?php echo $block->getMeasurmentIDGA4() ?>',{'user_id': tvc_user_id,'send_page_view' : false,'non_interaction': true});
        }

        if(tvc_ads_feature === 1){
            gtag('set','allow_ad_personalization_signals', false );
        }

        if(tvc_ip === 1){
            gtag('event', 'IP Anonymization', { 'anonymize_ip': true });
        }

        require(
            ['Tatvic_ActionableGoogleAnalytics/js/ga4script','jquery'],
            function(ga4_script){
                var obj = new ga4_script();
                obj.custom_dimentions();
                obj.custom_metrics();
            }
        );
    </script>
    <!-- End Global site tag (gtag.js) - Google Analytics 4 -->
<?php } ?>

<?php if($block->getUaIDBoth() && $block->getMeasurmentIdBoth() && $block->mode() === "both"){ ?>
    <!-- Global site tag (gtag.js) - Google Analytics Both -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $block->getMeasurmentIDGA4() ?>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', '<?php echo $block->getMeasurmentIdBoth() ?>',{'send_page_view' : false,'non_interaction': true});
        gtag('config', '<?php echo $block->getUaIDBoth() ?>',{'send_page_view' : false,'non_interaction': true});

        if (tvc_user_id !== '') {
            gtag('config', '<?php echo $block->getMeasurmentIdBoth() ?>',{'user_id': tvc_user_id,'send_page_view' : false,'non_interaction': true});
        }

        if(tvc_ads_feature === 1){
            gtag('set','allow_ad_personalization_signals', false );
        }

        if(tvc_ip === 1){
            gtag('event', 'IP Anonymization', { 'anonymize_ip': true });
        }

        require(
            ['Tatvic_ActionableGoogleAnalytics/js/bothscript','jquery'],
            function(both_script){
                var obj = new both_script();
                obj.custom_dimentions();
                obj.custom_metrics();
            }
        );
    </script>
    <!-- End Global site tag (gtag.js) - Google Analytics Both -->
<?php } ?>


<?php if($block->getGtm() == 0) { ?>
    <script>
        // Start Google Tag Manager
        (function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js' });
            var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-PM9RR2G');
        // End Google Tag Manager
    </script>
<?php } ?>

<?php


if($get_action == $get_action){
    echo "<script>
            var tvc_form =" . $formField . ";
            var tvc_user =" . json_encode($user) . ";
            exec_tvc_scroll = true;
            
    </script>";
}

if ($block->isHomePage() == 1) {
    
    $catProd = $block->getHomePageCatProd();
    $brandProd = $block->getProductsByManufacturer();

    if($block->getBestSeller() == 1){
        $bestSeller = $block->getBestSellerProducts();
    }else{
        $bestSeller = 'null';
    }
    echo "<script>
                var tvc_cat_prod = ". $catProd .";
                var tvc_brand_prod = ". $brandProd .";
                var tvc_best_seller = ". $bestSeller .";
                exec_tvc_t_hi = true;
         </script>";
}

if ($get_action == 'catalog_product_view') {
    echo "<script>
                var tvc_pp = " . $tvc_data . ";
                var tvc_rp = tvc_pp[0];
                var tvc_usp = tvc_pp[1];
                exec_tvc_t_ppv = true;
		</script>";
}

if ($get_action == 'catalog_category_view') {
    echo "<script>
                var tvc_pgc =" . $tvc_data . ";
                exec_tvc_t_c = true;
		</script>";
}

if ($get_action == 'catalogsearch_result_index') {
    echo "<script>
            var tvc_ps =" . $tvc_data . ";
            exec_tvc_t_cs = true;
    </script>";
}

if ($get_action == 'cms_index_noRoute') {
    echo "<script>

        require([ 'jquery','domReady'], function (jQuery,domReady) {
            ga('send', 'event', '404_error', '404', document.location.href, { 'nonInteraction': 1 });
        });

    </script>";
}

if ($get_action == 'checkout_cart_index') {
    echo "<script>
                var tvc_remove =" . $tvc_data . ";
                exec_tvc_t_dc = true;
        </script>";
}

if ($block->getCheckoutActionName() == 'firecheckout_index_index') {
    $tvc_data = $block->checkout_index_index();
    echo "<script>
                var tvc_ch ='" . $tvc_data . "';
                var t_keys = Object.keys(tvc_ch);
                var t_last = t_keys[tvc_ch.length-1];
                exec_tvc_t_checkout = true;
                if(tvc_form == 1){
                    exec_tvc_t_fft = true;
                }
    </script>";
}

if ($get_action == 'checkout_onepage_success') {
    echo "<script>
                var tvc_oo =" . $tvc_data . ";
                var t_keys = Object.keys(tvc_oo);
                var t_last = t_keys[tvc_oo.length-1];
                var tvc_oc = tvc_oo.pop(tvc_oo[t_last]);
                exec_tvc_t_thnx = true;
		</script>";
}