<?php
/**
 * PIT Solutions
 *
 * NOTICE OF LICENSE
 * This source file is licenced under Webshop Extensions software license.
 * Once you have purchased the software with PIT Solutions AG or one of its
 * authorised resellers and provided that you comply with the conditions of this contract,
 * PIT Solutions AG grants you a non-exclusive license, unlimited in time for the usage of
 * the software in the manner of and for the purposes specified in the documentation according
 * to the subsequent regulations.
 *
 * @category Pits
 * @package  Pits_GiftWrap
 * @author   Pit Solutions Pvt. Ltd.
 * @copyright Copyright (c) 2021 PIT Solutions AG. (www.pitsolutions.ch)
 * @license https://www.webshopextension.com/en/licence-agreement/
 */

use Magento\Framework\Pricing\Helper\Data;

$giftWrapPrice = $block->getGiftWrapPrice();
$priceHelper = $this->helper(Data::class);
$item = $block->getItem();
$itemGiftWrapData = $block->getQuoteItemGiftWrapData();
$helper = $this->helper('\Magento\Checkout\Helper\Cart');
if (($block->hasTwoMoreInCart() || !$block->isShowSummary()) && $block->canItemWrap($item)): ?>
<div class="gift-default-wrap" id="giftwrap-item-<?= $item->getId() ?>"
     data-bind="scope: 'giftwrap-item-<?= $item->getId() ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
{
            "#giftwrap-item-<?= $item->getId() ?>": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "giftwrap-item-<?= $item->getId() ?>": {
                        "component": "Pits_GiftWrap/js/view/checkout/cart/item/renderer",
                        "orderItemId": "<?= $item->getId() ?>",
                        "giftWrapData": <?= $itemGiftWrapData ?>,
                        "giftWrapSaveUrl": "<?= $block->getUrl('giftWrap/giftWrap/save') ?>",
                        "giftWrapRemoveUrl": "<?= $block->getUrl('giftWrap/giftWrap/delete') ?>",
                        "giftWrapLabelWithPrice": "<?= __(
                            $block->getGiftWrapTitle() . ' %1',
                            $priceHelper->currency($giftWrapPrice, true, false)
                        ) ?>",
                        "isWholeCart": false
                        }
                    }
                }
            }
        }
    </script>
    <!--<div class="item-gift-wrap-note"><?= $block->getItemWrapNote() ?></div>
    <div class="item-gift-wrap-note">By checking this option, we will wrap this product as gift.<a id="modal-btn" data-src="https://player.vimeo.com/video/886426066?badge=0&autoplay=1&loop=1"><b>Know more</b></a></div>-->
    <div class="item-gift-wrap-note">By checking this option, we will wrap this product as gift.<div data-mage-init='{"giftmodal": {"target": "#modal-contentnew"}}'></div>
    </div>
    <a id="open-btn"><button class="modal-button" href="#myModalnew" style="background:white;padding:0px;color:black">Show video</button></a>

<div style="display: none">
    <div id="modal-contentnew" >
        <div style="padding:130.78% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/886426066?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Reel 13_Asopalav_23Oct2023"></iframe></div>
    </div>
</div>
<!-- Trigger/Open The Modal -->
<!--<button class="modal-button" href=<?= "#myModal".$item->getId() ?>>Open Modal</button>-->

</div>
<?php endif; ?>
<script>
    require([
        'jquery',
    ],  
    function ($) {
        $("#open-btn").on('click',function(){
            $("#modal-contentnew").modal("openModal");
        });
    });
   
</script>
<script>
    // Get the button that opens the modal
    var btn = document.querySelectorAll("button.modal-button");
    
    // All page modals
    var modals = document.querySelectorAll('.giftwrep-modal');
    
    // Get the <span> element that closes the modal
    var spans = document.getElementsByClassName("close");
    
    // When the user clicks the button, open the modal
    for (var i = 0; i < btn.length; i++) {
     btn[i].onclick = function(e) {
        e.preventDefault();
        modal = document.querySelector(e.target.getAttribute("href"));
        modal.style.display = "block";
     }
    }
    
    // When the user clicks on <span> (x), close the modal
    for (var i = 0; i < spans.length; i++) {
     spans[i].onclick = function() {
        for (var index in modals) {
          if (typeof modals[index].style !== 'undefined') modals[index].style.display = "none";    
        }
     }
    }
    
    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target.classList.contains('modal')) {
         for (var index in modals) {
          if (typeof modals[index].style !== 'undefined') modals[index].style.display = "none";    
         }
        }
    }
</script>
<style>
    /* The Modal (background) */
.giftwrep-modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 100; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 40%;
    top: 0;
    width: 25%; /* Full width */
    /*height: 50%; /* Full height 
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.giftwrep-modal-content {
    position: relative;
    background-color: #fefefe;
    margin: auto;
    padding: 0;
    border: 1px solid #888;
    width: 80%;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
    -webkit-animation-name: animatetop;
    -webkit-animation-duration: 0.4s;
    animation-name: animatetop;
    animation-duration: 0.4s
}

/* Add Animation */
@-webkit-keyframes animatetop {
    from {top:-300px; opacity:0}
    to {top:0; opacity:1}
}

@keyframes animatetop {
    from {top:-300px; opacity:0}
    to {top:0; opacity:1}
}

/* The Close Button */
.close {
    color: white;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}

</style>