<?php
/**
 * PIT Solutions
 *
 * NOTICE OF LICENSE
 * This source file is licenced under Webshop Extensions software license.
 * Once you have purchased the software with PIT Solutions AG or one of its
 * authorised resellers and provided that you comply with the conditions of this contract,
 * PIT Solutions AG grants you a non-exclusive license, unlimited in time for the usage of
 * the software in the manner of and for the purposes specified in the documentation according
 * to the subsequent regulations.
 *
 * @category Pits
 * @package  Pits_GiftWrap
 * @author   Pit Solutions Pvt. Ltd.
 * @copyright Copyright (c) 2021 PIT Solutions AG. (www.pitsolutions.ch)
 * @license https://www.webshopextension.com/en/licence-agreement/
 */

use Magento\Framework\Pricing\Helper\Data;

$giftWrapPrice = $block->getGiftWrapPrice();
$priceHelper = $this->helper(Data::class);
$item = $block->getItem();
$itemGiftWrapData = $block->getQuoteItemGiftWrapData();
$helper = $this->helper('\Magento\Checkout\Helper\Cart');
if (($block->hasTwoMoreInCart() || !$block->isShowSummary()) && $block->canItemWrap($item)): ?>
<div class="gift-default-wrap" id="giftwrap-item-<?= $item->getId() ?>"
     data-bind="scope: 'giftwrap-item-<?= $item->getId() ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
{
            "#giftwrap-item-<?= $item->getId() ?>": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "giftwrap-item-<?= $item->getId() ?>": {
                        "component": "Pits_GiftWrap/js/view/checkout/cart/item/renderer",
                        "orderItemId": "<?= $item->getId() ?>",
                        "giftWrapData": <?= $itemGiftWrapData ?>,
                        "giftWrapSaveUrl": "<?= $block->getUrl('giftWrap/giftWrap/save') ?>",
                        "giftWrapRemoveUrl": "<?= $block->getUrl('giftWrap/giftWrap/delete') ?>",
                        "giftWrapLabelWithPrice": "<?= __(
                            $block->getGiftWrapTitle() . ' %1',
                            $priceHelper->currency($giftWrapPrice, true, false)
                        ) ?>",
                        "isWholeCart": false
                        }
                    }
                }
            }
        }
    </script>
    <div class="item-gift-wrap-note"><?= $block->getItemWrapNote() ?></div>
</div>
<?php endif; ?>