<?php
/**
 * PIT Solutions
 *
 * NOTICE OF LICENSE
 * This source file is licenced under Webshop Extensions software license.
 * Once you have purchased the software with PIT Solutions AG or one of its
 * authorised resellers and provided that you comply with the conditions of this contract,
 * PIT Solutions AG grants you a non-exclusive license, unlimited in time for the usage of
 * the software in the manner of and for the purposes specified in the documentation according
 * to the subsequent regulations.
 *
 * @category Pits
 * @package  Pits_GiftWrap
 * @author   Pit Solutions Pvt. Ltd.
 * @copyright Copyright (c) 2021 PIT Solutions AG. (www.pitsolutions.ch)
 * @license https://www.webshopextension.com/en/licence-agreement/
 */

use Pits\GiftWrap\Block\Checkout\MultishippingGiftOptions;

$allCartGiftActive = false;

/** @var GiftOptions $block */
?>

<?php if ($block->isGiftWrap()): ?>
    <?php $allCartGiftActive = true; ?>
<dl class="giftwrap-applied">
    <dt>
        <img src="<?= $block->getGiftWrapImagePath() ?>">
        <b class="giftwrap-applied-title"><?= __('Gift Wrapping applied (All Cart)') ?></b>
    </dt>
    <?php if ($message = $block->getGiftMessage()): ?>
        <dd><?= $message ?></dd>
    <?php endif ?>
</dl>          
<?php endif; ?>

<?php $item = $block->getParentBlock()->getItem(); ?>
<?php echo $item->getShippingAddressId() ?>
<?php if ($block->isGiftWrap($item->getQuoteItemId()) && ($block->checkSingleProduct($item->getQuoteItemId()) > 1 || !$allCartGiftActive)): ?>
    <dl class="giftwrap-applied">
        <dt>
            <img src="<?= $block->getGiftWrapImagePath() ?>">
            <b class="giftwrap-applied-title"><?= __('Gift Wrapping applied') ?></b>
        </dt>
        <?php if ($message = $block->getGiftMessage($item->getQuoteItemId())): ?>
            <dd><?= $message ?></dd>
        <?php endif ?>
    </dl>
<?php endif ?>
