<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */

$giftValue = $block->getOrder()->getOrderGift();
$flag = false;
$viewModel = $block->getData("viewModel");
$priceHelper = $viewModel->getdata(); // Instance of Pricing Helper
$price =  1000; //Your Price
?>
    
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= /* @noEscape */ $block->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
    <tr class="<?= /* @noEscape */ $_code?>">
        <th <?= /* @noEscape */ $block->getLabelProperties()?> scope="row">
            <?php if ($_total->getStrong()):?>
            <strong><?= /* @noEscape */ $block->escapeHtml($_total->getLabel());?></strong>
            <?php else:?>
                <strong><?= /* @noEscape */ $block->escapeHtml($_total->getLabel());?></strong>
            <?php endif?>
         
        </th>
        <td <?= /* @noEscape */ $block->getValueProperties()?> 
            data-th="<?= /* @noEscape */ $block->escapeHtml($_total->getLabel());?>">
            <?php if ($_total->getStrong()):?>
            <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
            <?php else:?>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif?>
                <?php if ($giftValue && !$_total->getLabel()):?>
                    <?= /* @noEscape */ __($giftValue); ?> 
                <?php endif; ?>   
        </td>
        <?php if (!$flag) {?>
            <tr class="<?= /* @noEscape */ $_code?>"> 
            <th <?= /* @noEscape */ $block->getLabelProperties()?> scope="row">
             
                <?php if ($giftValue):?>
                     <strong><?= /* @noEscape */ __('Gift Card'); ?> </strong>
                 <?php endif; ?>   
            </th>
            <td <?= /* @noEscape */ $block->getValueProperties()?> >                
                <?php if ($giftValue):?>
                     <?= /* @noEscape */ $priceHelper->currency(-$giftValue, true, false); ?> 
                 <?php endif; ?>   
            </td>
            </tr>
            <?php $flag=true; ?>        
    </tr>
    <?php } ?>
    <?php endif ?>
<?php endforeach ?>
