<?php
/**
 * @category Mageants GiftCard
 * @package Mageants_GiftCard
 * @copyright Copyright (c) 2016 Mageants
 * @author Mageants Team <support@mageants.com>
 */
?>

<div id="cart-totals" class="cart-totals" data-bind="scope:'block-totals'">
    <script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app":  <?= /* @noEscape */ $block->getJsLayout();?>
                }
            }
    </script>
</div>
